# 批量测试结果 - 2025-08-13 03:57:04
============================================================


## 模型: edsr_liif_ablation_e
模型路径: ./save_model_jittor_align/edsr_liif_ablation_e/epoch-best.pth
test-div2k-12.yaml: 23.2826
test-div2k-18.yaml: 21.8190
test-div2k-2.yaml: 34.2042
test-div2k-24.yaml: 20.9087
test-div2k-3.yaml: 30.5980
test-div2k-30.yaml: 20.2606
test-div2k-4.yaml: 28.6881
test-div2k-6.yaml: 26.1843
----------------------------------------

## 模型: edsr_liif_baseline
模型路径: ./save_model_jittor_align/edsr_liif_baseline/epoch-best.pth
test-b100-2.yaml: 31.9656
test-b100-3.yaml: 28.9162
test-b100-4.yaml: 27.4201
test-b100-6.yaml: 25.4437
test-b100-8.yaml: 24.4984
test-div2k-12.yaml: 23.2724
test-div2k-18.yaml: 21.8032
test-div2k-2.yaml: 34.2067
test-div2k-24.yaml: 20.8901
test-div2k-3.yaml: 30.5898
test-div2k-30.yaml: 20.2399
test-div2k-4.yaml: 28.6755
test-div2k-6.yaml: 26.1780
test-set14-2.yaml: 33.2796
test-set14-3.yaml: 30.0816
test-set14-4.yaml: 28.3497
test-set14-6.yaml: 25.7091
test-set14-8.yaml: 24.4626
test-set5-2.yaml: 37.5987
test-set5-3.yaml: 34.0052
test-set5-4.yaml: 31.8420
test-set5-6.yaml: 28.4973
test-set5-8.yaml: 26.6393
test-urban100-2.yaml: 31.3438
test-urban100-3.yaml: 27.5854
test-urban100-4.yaml: 25.6176
test-urban100-6.yaml: 23.1439
test-urban100-8.yaml: 21.9284
----------------------------------------

## 模型: edsr_liif_ablation_c
模型路径: ./save_model_jittor_align/edsr_liif_ablation_c/epoch-best.pth
test-div2k-12.yaml: 23.2436
test-div2k-18.yaml: 21.7907
test-div2k-2.yaml: 34.1045
test-div2k-24.yaml: 20.8928
test-div2k-3.yaml: 30.5081
test-div2k-30.yaml: 20.2517
test-div2k-4.yaml: 28.5923
test-div2k-6.yaml: 26.1075
----------------------------------------

## 模型: rdn_liif_v1
模型路径: ./save_model_jittor_align/rdn_liif_v1/epoch-best.pth
test-div2k-12.yaml: 23.3343
test-div2k-18.yaml: 21.8612
test-div2k-2.yaml: 执行失败 (code=1)
[38;5;2m[i 0813 04:43:59.775990 84 compiler.py:956] Jittor(1.3.10.0) src: /home/sumeru-js-04/miniconda3/envs/liv/lib/python3.9/site-packages/jittor[m
[38;5;2m[i 0813 04:43:59.777196 84 compiler.py:957] g++ at /usr/bin/g++(11.4.0)[m
[38;5;2m[i 0813 04:43:59.777222 84 compiler.py:958] cache_path: /home/sumeru-js-04/.cache/jittor/jt1.3.10/g++11.4.0/py3.9.23/Linux-5.15.0-1xd1/IntelRCoreTMi9xd1/1234/default[m
[38;5;2m[i 0813 04:43:59.838616 84 install_cuda.py:96] cuda_driver_version: [12, 4][m
[38;5;2m[i 0813 04:43:59.841141 84 __init__.py:412] Found /home/sumeru-js-04/.cache/jittor/jtcuda/cuda12.2_cudnn8_linux/bin/nvcc(12.2.140) at /home/sumeru-js-04/.cache/jittor/jtcuda/cuda12.2_cudnn8_linux/bin/nvcc.[m
[38;5;2m[i 0813 04:43:59.887442 84 __init__.py:412] Found gdb(22.04.2) at /usr/bin/gdb.[m
[38;5;2m[i 0813 04:43:59.888897 84 __init__.py:412] Found addr2line(2.38) at /usr/bin/addr2line.[m
[38;5;2m[i 0813 04:43:59.929422 84 compiler.py:1013] cuda key:cu12.2.140[m
[38;5;2m[i 0813 04:44:00.114539 84 __init__.py:227] Total mem: 125.58GB, using 16 procs for compiling.[m
[38;5;2m[i 0813 04:44:00.147146 84 jit_compiler.cc:28] Load cc_path: /usr/bin/g++[m
[38;5;2m[i 0813 04:44:00.147157 84 jit_compiler.cc:31] Load nvcc_path: /home/sumeru-js-04/.cache/jittor/jtcuda/cuda12.2_cudnn8_linux/bin/nvcc[m
[38;5;2m[i 0813 04:44:00.241057 84 init.cc:63] Found cuda archs: [86,][m
[38;5;2m[i 0813 04:44:00.795443 84 __init__.py:412] Found mpicc(4.1.2) at /usr/bin/mpicc.[m
[38;5;2m[i 0813 04:44:01.015713 84 cuda_flags.cc:55] CUDA enabled.[m
[38;5;3m[w 0813 04:44:01.194275 84 __init__.py:1645] load parameter feat failed ...[m
[38;5;3m[w 0813 04:44:01.199579 84 __init__.py:1664] load total 307 params, 1 failed[m

val:   0%|          | 0/100 [00:00<?, ?it/s]
val 36.5327:   0%|          | 0/100 [00:06<?, ?it/s]
val 36.5327:   1%|          | 1/100 [00:06<11:20,  6.88s/it]
val 38.3588:   1%|          | 1/100 [00:09<11:20,  6.88s/it]
val 38.3588:   2%|▏         | 2/100 [00:09<07:13,  4.43s/it]
val 40.5943:   2%|▏         | 2/100 [00:16<07:13,  4.43s/it]
val 40.5943:   3%|▎         | 3/100 [00:16<08:38,  5.34s/it][38;5;2m[i 0813 04:44:17.327011 84 cuda_device_allocator.cc:30] 
=== display_memory_info ===
 total_cpu_ram: 125.6GB total_device_ram: 23.68GB
 hold_vars: 626 lived_vars: 69582 lived_ops: 69271
 name: sfrl is_device: 1 used:   328MB(1.89%) unused: 16.64GB(98.1%) ULB: 2.988GB ULBO: 2.988GB total: 16.96GB
 name: sfrl is_device: 1 used:     0 B(-nan%) unused:     0 B(-nan%) total:     0 B
 name: sfrl is_device: 0 used:     0 B(-nan%) unused:     0 B(-nan%) total:     0 B
 name: sfrl is_device: 0 used: 5.773MB(2.31%) unused: 244.2MB(97.7%) ULB:    36MB ULBO:    36MB total:   250MB
 name: sfrl is_device: 0 used:     0 B(-nan%) unused:     0 B(-nan%) total:     0 B
 name: temp is_device: 0 used:     0 B(-nan%) unused:     0 B(-nan%) total:     0 B
 name: temp is_device: 1 used:     0 B(0%) unused: 5.512GB(100%) total: 5.512GB
 cpu&gpu: 22.71GB gpu: 22.47GB cpu:   250MB
 free: cpu(91.42GB) gpu(944.9MB)
 swap: total(    0 B) last(    0 B)
===========================
[m

                                                            
Traceback (most recent call last):
  File "/home/sumeru-js-04/Projects/Qwen/LIIF/liif_jittor/test.py", line 115, in <module>
    res = eval_psnr(loader, model,
  File "/home/sumeru-js-04/Projects/Qwen/LIIF/liif_jittor/test.py", line 81, in eval_psnr
    val_res.add(res.item(), inp.shape[0])
RuntimeError: [38;5;1m[f 0813 04:44:17.327125 84 executor.cc:686] 
Execute fused operator(5/24746) failed. 
[JIT Source]: /home/sumeru-js-04/.cache/jittor/jt1.3.10/g++11.4.0/py3.9.23/Linux-5.15.0-1xd1/IntelRCoreTMi9xd1/1234/default/cu12.2.140/jit/__opkey0_broadcast_to__Tx_float32__DIM_7__BCAST_19__opkey1_reindex__Tx_float32__XDIM_4__YD___hash_8f91e55bdd99985a_op.cc 
[OP TYPE]: fused_op:( broadcast_to, reindex, binary.multiply, reduce.add,)
[Input]: float32[64,3,3,3,]encoder.SFENet1.weight, float32[1,3,600,1020,], 
[Output]: float32[1,64,600,1020,], 
[Async Backtrace]: not found, please set env JT_SYNC=1, trace_py_var=3 
[Reason]: [38;5;1m[f 0813 04:44:17.327064 84 cuda_device_allocator.cc:31] Unable to alloc cuda device memory for size 5904603648[m[m
**********
Async error was detected. To locate the async backtrace and get better error report, please rerun your code with two enviroment variables set:
>>> export JT_SYNC=1
>>> export trace_py_var=3
test-div2k-24.yaml: 20.9379
test-div2k-3.yaml: 30.6891
test-div2k-30.yaml: 20.2851
test-div2k-4.yaml: 28.7840
test-div2k-6.yaml: 26.2729
----------------------------------------

## 模型: edsr_liif_ablation_d
模型路径: ./save_model_jittor_align/edsr_liif_ablation_d/epoch-best.pth
test-div2k-12.yaml: 23.2366
test-div2k-18.yaml: 21.7819
test-div2k-2.yaml: 34.2281
test-div2k-24.yaml: 20.8723
test-div2k-3.yaml: 30.5865
test-div2k-30.yaml: 20.2258
test-div2k-4.yaml: 28.6680
test-div2k-6.yaml: 26.1541
----------------------------------------
